// This file is auto-generated by controllers/bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// controllers/bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import BmiController from "controllers/bmi_controller"
application.register("bmi", BmiController)

import CarouselController from "controllers/carousel_controller"
application.register("carousel", CarouselController)

import CptSearchController from "controllers/cpt_search_controller"
application.register("cpt-search", CptSearchController)

import DropzoneController from "controllers/dropzone_controller"
application.register("dropzone", DropzoneController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import NestedFormController from "controllers/nested_form_controller"
application.register("nested-form", NestedFormController)
