require "prawn"
require "prawn/table"

class PrescriptionGenerator
  def initialize(medication)
    @medication = medication
    @patient = medication.patient
    @provider = medication.prescribed_by.provider # The User's Provider Profile
    @organization = medication.patient.organization
  end

  def call
    Prawn::Document.new do |pdf|
      # --- Header ---
      pdf.text @organization.name.upcase, size: 16, style: :bold, align: :center
      pdf.text "Office: #{@provider.organization.facilities.first&.phone || 'N/A'}", align: :center, size: 10
      pdf.move_down 20
      pdf.stroke_horizontal_rule
      pdf.move_down 20

      # --- Doctor & Patient Grid ---
      data = [
        [
          "<b>PRESCRIBER:</b>\n#{@provider.full_name}\nNPI: #{@provider.npi}\nDEA: #{@provider.dea_number}\nLic: #{@provider.license_number}",
          "<b>PATIENT:</b>\n#{@patient.full_name}\nDOB: #{@patient.date_of_birth&.strftime('%m/%d/%Y')}\n#{@patient.street_address}\n#{@patient.city}, #{@patient.state} #{@patient.zip_code}"
        ]
      ]

      pdf.table(data, width: 540, cell_style: { inline_format: true, border_width: 0, padding: 0 })
      pdf.move_down 40

      # --- The Script (Rx Symbol) ---
      pdf.text "Rx", size: 40, style: :bold
      pdf.move_down 10

      pdf.text @medication.name.upcase, size: 14, style: :bold
      pdf.text @medication.sig, size: 12
      pdf.move_down 10

      pdf.text "Qty: #{@medication.quantity} (#{@medication.quantity_unit})", size: 12
      pdf.text "Refills: #{@medication.refills}", size: 12

      if @medication.pharmacy_note.present?
        pdf.move_down 10
        pdf.text "Note to Pharmacy: #{@medication.pharmacy_note}", size: 10, style: :italic
      end

      # --- Security Footer ---
      pdf.move_down 100
      pdf.stroke_horizontal_rule
      pdf.move_down 10

      # Signature Line
      pdf.text "Signature: __________________________________________________", size: 12
      pdf.text "Electronically signed by #{@provider.full_name} on #{Date.today.strftime('%m/%d/%Y')}", size: 8, color: "666666"

      pdf.move_down 20
      pdf.text "Generated by AppIdeaEMHR - ID: #{@medication.id}", size: 8, align: :center, color: "CCCCCC"
    end.render
  end
end
